spring:
  config:
    import:
      - nacos:application-nacos.yml
  cloud:
    nacos:
      discovery:
        server-addr: ${spring.cloud.nacos.config.server-addr}
        namespace: ${spring.cloud.nacos.config.namespace}
        group: xiao
        username: ${spring.cloud.nacos.config.username}
        password: ${spring.cloud.nacos.config.password}
      config:
        group: gateway-server
        refresh-enabled: true

# Actuator 配置
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always