nacos:
  common-group: nacos-common

spring:
  config:
    import:
      - nacos:application-nacos.yml
      - nacos:common-application-db.yml?server-addr=${spring.cloud.nacos.config.server-addr}&group=${nacos.common-group}
      - nacos:common-redis-config.yml?server-addr=${spring.cloud.nacos.config.server-addr}&group=${nacos.common-group}
  cloud:
    nacos:
      discovery:
        server-addr: ${spring.cloud.nacos.config.server-addr}
        namespace: ${spring.cloud.nacos.config.namespace}
        group: xiao
        username: ${spring.cloud.nacos.config.username}
        password: ${spring.cloud.nacos.config.password}
      config:
        group: product-service
        refresh-enabled: true

# Actuator 配置
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always