spring:
  profiles:
    active: @profileActive@
  cloud:
    nacos:
      config:
        server-addr: localhost:8848
        namespace: 6662f928-1f3c-453c-bb2d-083806cdc7d3
        username: nacos
        password: nacos