nacos:
  common-group: nacos-common

spring:
  config:
    import: #指定加载配置的方式以及文件
      - nacos:application-nacos.yml
      - nacos:application-billinglog.yml
      - nacos:common-rocketmq-zb-config.yml?server-addr=${spring.cloud.nacos.config.server-addr}&group=${nacos.common-group}
      - nacos:common-application-db.yml?server-addr=${spring.cloud.nacos.config.server-addr}&group=${nacos.common-group}
      - nacos:common-redis-config.yml?server-addr=${spring.cloud.nacos.config.server-addr}&group=${nacos.common-group}
  cloud:
    nacos:
      discovery:
        server-addr: ${spring.cloud.nacos.config.server-addr}
        namespace: ${spring.cloud.nacos.config.namespace}
        group: xiao
        username: ${spring.cloud.nacos.config.username}
        password: ${spring.cloud.nacos.config.password}
      config:
        server-addr: 10.108.183.17:8848
        namespace: 6662f928-1f3c-453c-bb2d-083806cdc7d3
        group: domestic-gateway
        refresh-enabled: true
        username: nacos
        password: nacos